name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build debug app
        run: ./gradlew assembleDebug --stacktrace
      - name: Attach universal APK file
        uses: actions/upload-artifact@main
        with:
          name: scjd-sbsp_debug_universal
          path: |
            app/build/outputs/apk/debug/scjd-sbsp_debug_universal.apk
            app/build/outputs/apk/debug/output-metadata.json
      - name: Attach arm64-v8a APK file
        uses: actions/upload-artifact@main
        with:
          name: scjd-sbsp_debug_arm64-v8a
          path: |
            app/build/outputs/apk/debug/scjd-sbsp_debug_arm64-v8a.apk
            app/build/outputs/apk/debug/output-metadata.json
      - name: Attach armeabi-v7a  APK file
        uses: actions/upload-artifact@main
        with:
          name: scjd-sbsp_debug_armeabi-v7a
          path: |
            app/build/outputs/apk/debug/scjd-sbsp_debug_armeabi-v7a.apk
            app/build/outputs/apk/debug/output-metadata.json
